#baseURL = 'https://ai-hed.com/'
baseURL= 'https://ai-hed.eu/'
languageCode = 'en-uk'
title = 'AI-HED'
theme = "Hugo-Now-UI-Pro"
[params]
logo = "/images/ai-hed-shorthandlogo.svg"
  [params.umami]
  active = true
  siteId = 'dc13752c-d59c-44c8-95bc-e15254ed9425'
  src = 'https://nash.lisboncollective.com/script.js'
  [params.showLastUpdated]
  enabled = true
  # Use "2006-01-02" to define a custom date format
  dateFormat = "January 2, 2006"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = false
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

[security.funcs]
  getenv = ['^HUGO_', '^CI$', '^SLUG$']

[menu]
  [[menu.main]]
    name = "About"
    weight = 1
  [[menu.footer_two]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/ai-hed/"